### ISSUE TITLE
Bài 6 câu 3:

### ISSUE THREAD

**Issue by PhamThanhPhongPN** [PhamThanhPhongPN/Lop-10A02-Nhom-07#13]

**Comment by Nguyen-Hoang-Bao-Dung** [comment]
-Việc giải toán trên máy tính giống như việc giải quyết vấn đề ngoài đời thực:
+VD1: Giải quyết nồi canh bị mặn
B1: Xác định nguyên nhân nồi canh bị mặn(cho nhiều muối).
B2: Tham khảo tài liệu ẩm thực để đưa ra giải pháp phù hợp giúp nồi canh bớt mặn hơn.
B3: Bắt đầu thực hiện giải pháp(cho thêm đường vào nồi canh).
B4: Điều chỉnh lượng đường cho vào vừa đủ để giúp nồi canh bớt gắt và làm dịu vị giác.
B5: Ghi chép lại cách xử lí vào cuốn sách nấu ăn để sau này áp dụng.
+VD2: Giảng hoà hai bạn đang cãi nhau
B1: Xác định nguyên nhân 2 bạn cãi nhau(hiểu lầm).
B2: Sử dụng những điều đã biết đưa ra giải pháp làm hoà cho 2 bạn.
B3: Bắt đầu thực hiện giải pháp giúp 2 bạn làm hoà(giúp 2 bạn nói chuyện với nhau để hoá giải hiểu lầm).
B4: Nếu 2 bạn vẫn không chịu nói chuyện với nhau thì phải làm dịu cơn giận của 2 bạn trước(kể chuyện cười).
B5: Viết vào nhật kí việc tốt mà mình vừa làm được.
